In [1]:
import numpy as np

In [3]:
a = np.array([[5,-1],[9,1],[6,0]])

In [4]:
a

array([[ 5, -1],
       [ 9,  1],
       [ 6,  0]])

In [5]:
a.transpose()

array([[ 5,  9,  6],
       [-1,  1,  0]])

In [6]:
C = a

In [8]:
C.transpose()

array([[ 5,  9,  6],
       [-1,  1,  0]])

In [9]:
C

array([[ 5, -1],
       [ 9,  1],
       [ 6,  0]])

In [10]:
A = np.array([[1,2,3],[2,7,4]])

In [11]:
A

array([[1, 2, 3],
       [2, 7, 4]])

In [13]:
A-C.transpose()

array([[-4, -7, -3],
       [ 3,  6,  4]])

In [14]:
D=np.array([[3,-2,-1],[1,2,3]])

In [15]:
D

array([[ 3, -2, -1],
       [ 1,  2,  3]])

In [16]:
3D

SyntaxError: invalid syntax (<ipython-input-16-bae8ed496cfc>, line 1)

In [17]:
3*D

array([[ 9, -6, -3],
       [ 3,  6,  9]])

In [19]:
C.transpose()+(3*D)

array([[14,  3,  3],
       [ 2,  7,  9]])

In [20]:
B=np.array([[1,-1],[0,1]])

In [21]:
B

array([[ 1, -1],
       [ 0,  1]])

In [22]:
A*B

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [29]:
B*A.transpose()

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [24]:
A.transpose()

array([[1, 2],
       [2, 7],
       [3, 4]])

In [25]:
B

array([[ 1, -1],
       [ 0,  1]])

In [28]:
B*B*B*B

array([[1, 1],
       [0, 1]])

In [30]:
A

array([[1, 2, 3],
       [2, 7, 4]])

In [31]:
B

array([[ 1, -1],
       [ 0,  1]])

In [32]:
b2 = B+B

In [33]:
b2

array([[ 2, -2],
       [ 0,  2]])

In [109]:
# Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': [len(A),len(A[0])],
    'B': [len(B),len(B[0])],
    'C': [len(C),len(C[0])],
    'D': [len(D),len(D[0])],
    'u': len(u),
    'v': len(v)
}

# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6
u_plus_v = u+v            # u+v
u_minus_v = u-v          # u-v
alpha_times_u = 6*u       # alpha * u, alpha = 6
u_dot_v = u.dot(v)             # u . v
norm_u = np.linalg.norm(u)          # ||u|| 


# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = None             # A + C
A_minus_Ctranspose = A-C.transpose() # A - C.T
Ctranspose_plus_3D = C.transpose() + 3*D   # C.T + 3*D
B_times_A = np.matmul(B,A)            # B*A
B_times_Atranspose = None   # B*A.T

# Q4: (bonus)

B_times_C = None       # B*C
C_times_B = np.matmul(C,B)            # C*B
B_exp_4 = B**4              # B^4
A_times_Atranspose = np.matmul(A,A.transpose())   # A*A.T
Dtranspose_times_D = np.matmul(D.transpose(),D)   # D.T*D


In [115]:
alpha = 6
u_plus_v 

array([ 9,  7, -4,  9])

In [103]:
B_times_Atranspose 

In [52]:
B*C

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [53]:
C*B

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [54]:
B*B*B*B

array([[1, 1],
       [0, 1]])

In [56]:
B**4

array([[1, 1],
       [0, 1]])

In [61]:
np.matmul(D.transpose(),D)

array([[10, -4,  0],
       [-4,  8,  8],
       [ 0,  8, 10]])

In [62]:
u

array([ 6,  2, -3,  5])

In [64]:
np.linalg.norm(u)

8.6023252670426267

In [93]:
np.matmul(B,A.transpose())

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [96]:
B**4

array([[1, 1],
       [0, 1]])

In [88]:
dimensions

{'A': [2, 3], 'B': [2, 2], 'C': [3, 2], 'D': [2, 3], 'u': 4, 'v': 4}